name: Unit test workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.os }} ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'source/app/pyproject.toml'
      - name: Install Tox and any other packages
        run: |
          pip install --upgrade pip
          pip install tox
          pip install tox-gh-actions
      - name: Cache tox and mypy
        uses: actions/cache@v3
        with:
          path: |
            .tox
            .mypy_cache
          key: ${{ matrix.os }}-${{ matrix.python}}-tox-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('tox.ini') }}-${{ hashFiles('.github/workflows/unit-test-workflow.yml') }}
      - name: Run Tox
        run: tox